//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THTMDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaodientuEntities : DbContext
    {
        public BaodientuEntities()
            : base("name=BaodientuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AD> ADs { get; set; }
        public virtual DbSet<BaiBao> BaiBaos { get; set; }
        public virtual DbSet<Danhmuc> Danhmucs { get; set; }
        public virtual DbSet<DoiTac> DoiTacs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<LoaiQC> LoaiQCs { get; set; }
        public virtual DbSet<QuangCao> QuangCaos { get; set; }
        public virtual DbSet<TacGia> TacGias { get; set; }
        public virtual DbSet<TTDH> TTDHs { get; set; }
        public virtual DbSet<TTQC> TTQCs { get; set; }
        public virtual DbSet<TTBB> TTBBs { get; set; }
    }
}
