//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public int MaQC { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> IDLoaiQC { get; set; }
    
        public virtual LoaiQC LoaiQC { get; set; }
    }
}
